### ISSUE TITLE
Aircraft Carrier and Carrier Flagships crash the game if you merge it with other paths

### ISSUE THREAD

**Issue by RedWirePlatinumTwo** [doombubbles/ultimate-crosspathing#10]
As soon as I try mixing anything with a maxed top-path monkey buccaneer, the game instantly crashes. If I only stopped at Aircraft Carrier, the game would instead crash if anything got within the range of the buccaneer. 

(Other than that, the mod is amazing)

**Comment by MagicGonads** [comment]
I think it's the second path tier 3 upgrade that's incompatible with top path tier 4, but both paths are fully compatible by themselves along with the bottom path
