### ISSUE TITLE
crashing game

### ISSUE THREAD

**Issue by YoungZozol** [doombubbles/ultimate-crosspathing#100]
# Tower Crash / Fail

when i upgrade monkey village and ship to ultimate crosspathing game crashes and turning off can you do update for it

**Comment by DarkNebulousSpaector** [comment]
same

**Comment by DarkNebulousSpaector** [comment]
happens apon the start of the next round

**Comment by Colotov-Mocktail** [comment]
can also confirm. having the monkey village have the top and middle path both be 3rd tier crashes the game

**Comment by doombubbles** [comment]
Crashes like these are fixed with the latest [MelonLoader 0.6.1 update](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer
