### ISSUE TITLE
3-0-4 Heli crash

### ISSUE THREAD

**Issue by sdapalsch** [doombubbles/ultimate-crosspathing#102]
# Tower Crash / Fail

### Mod Version

1.3.7

### Mod Helper Version

3.1.6

### Tower Crosspaths

3-0-4 Heli Tower

### Description

After upgrading from 3-0-3 to 3-0-4 it crashes mid-round. I'm assuming when it would attempt to call in mini-comanches.

### Other Mods

![Capture](https://user-images.githubusercontent.com/16731967/230244676-1d4b21cd-6793-4146-a608-d1ede6f39883.PNG)

### Logs

[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/11165309/Latest.log)

**Comment by doombubbles** [comment]
Crashes like these are fixed with the latest [MelonLoader 0.6.1 update](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer
