### ISSUE TITLE
all towers not working

### ISSUE THREAD

**Issue by Supamonkey** [doombubbles/ultimate-crosspathing#103]
no towers have ultimate crosspathing capabilities and i know there's a fix I just don't know how to do it.

**Comment by SuperCatTheGod** [comment]
I've been having the same if not similar problem recently and I've recently updated both the mod helper and crosspath.
I have an image of the error message
![image](https://user-images.githubusercontent.com/123556452/230385008-e7c28da2-3022-4ea3-a82b-6b63b4efd9df.png)

**Comment by Supamonkey** [comment]
Yeah this is what i have been getting also and tried the same methods as you i just forgot to add the error (also I'm not sure if I've replied to you because I'm relatively new to github)

**Comment by SuperCatTheGod** [comment]
this is probably just they forgot to add the crosspath part of the mod back in or the mod is not detecting the towers. 
but I don't really know much about btd6 modding anyway so I probably am just making things up here (you did reply yes)

**Comment by doombubbles** [comment]
Please update to [MelonLoader 0.6.1](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer

**Comment by Supamonkey** [comment]
where exactly do i find " reworked instas" because i cant find it so i  dont think i have it

**Comment by doombubbles** [comment]
Yeah Insta Monkey Rework is a separate mod https://github.com/doombubbles/insta-monkey-rework#readme

**Comment by BraveCaperCat2** [comment]
> where exactly do i find " reworked instas" because i cant find it so i dont think i have it

uninstalling "Reworked Instas" fixed the mod temporarily, until it started breaking again - I then updated the version of MelonLoader, and it was fixed.
