### ISSUE TITLE
Towers fails to Ultimately Crosspath.

### ISSUE THREAD

**Issue by robloxking50** [doombubbles/ultimate-crosspathing#109]
# Installation Error

### Mod Version

1.4.0

### Mod Helper Version

3.1.6

### Description

When I have installed both, Ultimate Crosspathing and the Mod Helper and opened the game, this appears:
![image](https://user-images.githubusercontent.com/124338531/232177905-432821d5-b07b-4c0f-9d37-bd7a18122d32.png)

### Other Mods

All of the mods work except for Ultimate Crosspathing mod.
I have already removed all other mods and they are not causing the issue but here are the mods I regularly use:
![image](https://user-images.githubusercontent.com/124338531/232178750-d9f052fa-80c9-40eb-899b-48e14a115fee.png)

### Logs

[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/11238101/Latest.log)

**Comment by doombubbles** [comment]
Please update to [MelonLoader 0.6.1](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer

**Comment by robloxking50** [comment]
Thanks, I forgot about updating that.
