### ISSUE TITLE
Price Increases.

### ISSUE THREAD

**Issue by KTR1218** [doombubbles/ultimate-crosspathing#11]
Hi! Whenever I choose two paths, the third path costs 340,282,300,000,000,000,000,000,000,000,000,000,000 money. Please fix this!

**Comment by KTR1218** [comment]
![image](https://user-images.githubusercontent.com/90740537/133363674-e9ad98ed-9596-4c7c-ac82-034c703eaf19.png)

**Comment by MagicGonads** [comment]
This is because you haven't let it generate the crosspaths.
Try toggling on the Regenerate Towers and then look at the console and wait until it finishes.

**Comment by MagicGonads** [comment]
I managed to encounter this in vanilla in co-op during some lag on the next round start, so this seems to be how the game indicates that an upgrade can't be selected even when the button isn't disabled
