### ISSUE TITLE
Towers failing to load

### ISSUE THREAD

**Issue by aaronmansfield5** [doombubbles/ultimate-crosspathing#110]
# Tower Crash / Fail

### Mod Version

v1.4.0

### Mod Helper Version

v3.1.7

### Tower Crosspaths

All Towers any Crosspath

### Description

It will not load at all

### Other Mods

![image](https://user-images.githubusercontent.com/37600872/234393043-f8c7ab76-cf0e-4daa-8568-71f1fc64ac56.png)

### Logs

[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/11326420/Latest.log)

**Comment by doombubbles** [comment]
Just gotta update to [MelonLoader 0.6.1](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). You can also update through the MelonLoader installer
