### ISSUE TITLE
buccaneer can't pop camo leads

### ISSUE THREAD

**Issue by Crandall0** [doombubbles/ultimate-crosspathing#116]
# Tower Behavior Improvement

### Mod Version

1.4.4

### Mod Helper Version

3.1.15

### Tower Crosspaths

buccaneer 4/4/4

### Description

even though it has hot shot and crows nest, it can see the camo leads and fires at them, but the projectiles don't damage them

![image](https://github.com/doombubbles/ultimate-crosspathing/assets/81304240/414e318b-9ffb-4b9e-94f4-8aacb88ed1cd)

**Comment by doombubbles** [comment]
Fixed with latest release https://github.com/doombubbles/ultimate-crosspathing/releases/tag/1.4.5

**Comment by Crandall0** [comment]
:)
