### ISSUE TITLE
boat crosspaths not working

### ISSUE THREAD

**Issue by icantcomeupwith1** [doombubbles/ultimate-crosspathing#119]
# Tower Behavior Improvement

### Mod Version

v 1.4.5

### Mod Helper Version

v 3.1.16

### Tower Crosspaths

buccaneer

### Description

only 2 crosspaths are open at a time, like in vanilla

**Comment by doombubbles** [comment]
Update to 1.4.6 https://github.com/doombubbles/ultimate-crosspathing/releases/tag/1.4.6
