### ISSUE TITLE
Mod gets me flagged in singleplayer

### ISSUE THREAD

**Issue by CookieKiller2** [doombubbles/ultimate-crosspathing#120]
# Miscellaneous Bug

1.4.5 Mod Version

3.1.16 Mod Helper Version

### Description

i downloaded the mod, played it in singleplayer for medals and got flagged every time (3 accounts). when i disable the mod and try a new account, i dont get flagged.

### Other Mods
Faster forward, ultimate 5th tiers+, mega knowlege.

**Comment by doombubbles** [comment]
There's not really much that can be done about this really. I'm not going to try to subvert Ninja Kiwi in terms of what they deem to be worthy of flagging. Their stance has always been that you should be using a separate account for modding that you're ok with being flagged.
