### ISSUE TITLE
8 Towers are broken

### ISSUE THREAD

**Issue by S-s-Spudd** [doombubbles/ultimate-crosspathing#122]
# Tower Crash / Fail

### Mod Version

V1.4.8

### Mod Helper Version

V3.1.18

### Tower Crosspaths

Alchemist / Druids / EngineerMonkey / IceMonkeys / MonkeySubs / MortarMonkey / NinjaMonkey / WizardMonkeys

### Description

Launch the game and get told that 8 towers failed to load (ones listed above) 

### Other Mods

"BloonsMultiplier" / "Gain Knowledge on Round 100 and 125" / "Unlimited 5th Tiers +"

### Logs
![image_2024-04-11_091629030](https://github.com/doombubbles/ultimate-crosspathing/assets/77349475/b2acb57f-4967-4586-9ad2-9e6e2928fb8d)
![image_2024-04-11_091640417](https://github.com/doombubbles/ultimate-crosspathing/assets/77349475/85a51edf-a42d-4915-902e-a9406a69c932)

**Comment by doombubbles** [comment]
Fixed for btd6 42.1 with the new mod version https://github.com/doombubbles/ultimate-crosspathing/releases/tag/1.4.9

**Comment by S-s-Spudd** [comment]
Appreciated, will let you know if something else goes wrong. 👍

**Comment by Flipityflip** [comment]
Thanks 👍

**Comment by S-s-Spudd** [comment]
I have no issues anymore. Much appreciated for the fix 👍🏼
