### ISSUE TITLE
Game crashes when loading into a match with card monkey or industrial farmer

### ISSUE THREAD

**Issue by DarkTerraYT** [doombubbles/ultimate-crosspathing#124]
# Installation Error

### Mod Version

1.4.9

### Mod Helper Version

3.1.20

### Description

Whenever you have the card monkey installed, the game crashes when entering a match

### Other Mods

Card Monkey/industrial farmer, faster forward, instant degree, multicash, paths++, 4th paths, powers in shop

### Logs

no errors are logged, and there's even no crash log in the Bloons TD6 dump folder

**Comment by doombubbles** [comment]
Fixed with https://github.com/doombubbles/IndustrialFarmer/releases/tag/1.0.11 and https://github.com/doombubbles/card-monkey/releases/tag/1.2.10
