### ISSUE TITLE
Errors that occurred after updating to version 46.

### ISSUE THREAD

**Issue by 774401807** [doombubbles/ultimate-crosspathing#130]
# Tower Behavior Improvement

### Mod Version

1.5.2

### Mod Helper Version

3.3.4

### Tower Crosspaths

24towers

### Description

After updating to version 46, it stopped working. The previous version worked fine. I'm using MelonLoader version 0.6.5, and Mod Helper has been updated to the latest version. This mod's latest version is from October. Other mods are working fine.

**Comment by doombubbles** [comment]
Fixed in latest version https://github.com/doombubbles/ultimate-crosspathing/releases/tag/1.5.3
