### ISSUE TITLE
sniper crashes

### ISSUE THREAD

**Issue by EthereaI** [doombubbles/ultimate-crosspathing#14]
when using a 5-5-5 sniper and then placing a new sniper may or may not crash depending on the order you upgrade your original 555 sniper.

I did some testing and here are my results: (only mod installed is ultimate crosspathing)

Tests are written in chronological order, new test per line, 1st letter top, 2nd middle, 3rd bottom

500 540 545 then new 000 then 555, crash
000 then new 500 505 555, crash
000 then new 050 055 555, no crash
000 then new 050 550 555, no crash
050 550 555 then new 000, no crash

**Comment by MagicGonads** [comment]
The order shouldn't matter in theory, so this is very odd
some speculation:
elite defender is unable to use the elite sniper's ability so maybe if you upgrade to elite sniper from elite defender it doesn't properly apply the reload speed bonus to all snipers, which crashes the game when another sniper appears (or if another sniper exists)

**Comment by WTTG2Noir** [comment]
well idk if its fixed already but it works fine to me so prob the mod was missing another lib / mod to work correctly i guess
