### ISSUE TITLE
Monkey Buncaneer Failing to Load 

### ISSUE THREAD

**Issue by DieselWeasel1** [doombubbles/ultimate-crosspathing#27]
When the game loads up it loads the crosspathing mechanic for all of the towers. on this current version it fails to load the monkey bucaneer everytime meaning that tower and all towers following that cannot be crosspathed

![Screenshot (87)](https://user-images.githubusercontent.com/95841360/145340066-c3c845a3-a9ab-498a-acc0-6c3bb1f5ca8b.png)

**Comment by MrInfraRage** [comment]
thank you for posting this. I was wondering y all the support towers werent working. Hopefully the mod gets updated soon

**Comment by CK3ternity** [comment]
I'd been having this same problem all day, if you toggle "Debug: Regenerate Towers" in the mod options menu and restart the game, all towers except the buccaneer works.
