### ISSUE TITLE
Why is it so expensive??!?!!?

### ISSUE THREAD

**Issue by not-even-close** [doombubbles/ultimate-crosspathing#28]
Whenever i try to 5,5,5 a plane, helicopter, spike factory or banana farm it costs like 340 undecilion. Does anyone know why this is happening?

**Comment by CK3ternity** [comment]
There is an issue with the buccaneer right now, which makes all the towers after it not work. If you click Regenerate Towers in the mod options and restart the game, everything except the buccaneer should work again.

**Comment by not-even-close** [comment]
That solved it, thank you.
