### ISSUE TITLE
Lag spikes every 1 second

### ISSUE THREAD

**Issue by zAlfredoo** [doombubbles/ultimate-crosspathing#29]
The game lag spikes once about every second (all I have installed is mod helper and the ultimate crosspathing mod). Is there

**Comment by zAlfredoo** [comment]
Is there anything I can show you to help?*

**Comment by geezbeez1212** [comment]
yeah there's been lag spikes for me too

**Comment by doombubbles** [comment]
As far as I can tell this issue may be unavoidable. The mod doesn't perform any background tasks, which means that it's some normal game process that's lagging things somehow, likely under the weight of ~ tripling the number of TowerModels in the GameModel. I have no leads on being able to find that process, and no guarantees that I could optimize that process even if I found it, so we're sadly in a bit of a tough spot.

**Comment by doombubbles** [comment]
I've made some improvements in this area with v1.2.4
