### ISSUE TITLE
Paragon doesnt works on crosspathing 5-5-5

### ISSUE THREAD

**Issue by RazorWolvendom** [doombubbles/ultimate-crosspathing#31]
if you upgrade a single tower with tier 5 for all 3 paths it wont count as 3 separate tier 5 towers to merge the paragon  with:
0-0-5
0-5-0
5-0-0

![ScreenShot_20211226224929](https://user-images.githubusercontent.com/44827474/147420799-3edaf7a4-8a29-4b8f-95ad-924187024abd.png)
![ScreenShot_20211226224940](https://user-images.githubusercontent.com/44827474/147420811-0e7b1e6e-f9d8-424d-b280-63e59b01c061.png)

**Comment by Mani-cwaf** [comment]
> if you upgrade a single tower with tier 5 for all 3 paths it wont count as 3 separate tier 5 towers to merge the paragon with: 0-0-5 0-5-0 5-0-0
> 
> ![ScreenShot_20211226224929](https://user-images.githubusercontent.com/44827474/147420799-3edaf7a4-8a29-4b8f-95ad-924187024abd.png) ![ScreenShot_20211226224940](https://user-images.githubusercontent.com/44827474/147420811-0e7b1e6e-f9d8-424d-b280-63e59b01c061.png)

actually it does count but since order 66 gives 15 upgrades and a paragon is a 16 upgrade it won't work, try getting a 5-5-2 and a 0-0-5 and it'll work

**Comment by Kosmic-Gamer** [comment]
Also Try 5-5-4 and the other required T5
