### ISSUE TITLE
Mod crashes the game

### ISSUE THREAD

**Issue by GorillaGamerX** [doombubbles/ultimate-crosspathing#32]
every time i try to open the game with this mod on it crashes the game and even if i download newer versions it still crashes the game.

**Comment by mlgmacknoscopes** [comment]
it started happening to me after i turned on order 66. i forgot to turn it off and now the mod is unusable

**Comment by randomMokey** [comment]
uhmmm how do dowlode i dont know how

**Comment by RazorWolvendom** [comment]
> every time i try to open the game with this mod on it crashes the game and even if i download newer versions it still crashes the game.

did you check the cmd console for any errors?
