### ISSUE TITLE
Random money bug

### ISSUE THREAD

**Issue by BTD6Foxi** [doombubbles/ultimate-crosspathing#37]
Hello, I just recently found a bug in this mod. It is with the Sniper monkey. For some reason if you do a 1-4-5 sniper monkey, you will get a ton of supply crate drops. I will also supply this issue of an image.

![image](https://user-images.githubusercontent.com/99281666/153045430-9354a03a-5ef1-4c80-bfaa-12943e3aeb9c.png)

**Comment by doombubbles** [comment]
Don't remember when, but this was indeed fixed a while ago
