### ISSUE TITLE
whenever i open the game with the mod it just crashes once i hit play

### ISSUE THREAD

**Issue by Nickisnotfunny** [doombubbles/ultimate-crosspathing#38]
here is the error from the log
 [ERROR] Exception in Harmony patch of method void Assets.Scripts.Models.Profile.ProfileModel::Validate(Il2CppSystem.Runtime.Serialization.StreamingContext context):
System.NullReferenceException: Object reference not set to an instance of an object

**Comment by adamosama902** [comment]
the log ok what are we soposed to do

**Comment by Meplus455** [comment]
What we supposed to dooooo
