### ISSUE TITLE
this message keeps on popping up and i want to play co op so how do i make it stop and also it doesn't save my progress

### ISSUE THREAD

**Issue by Stateofawesome9** [doombubbles/ultimate-crosspathing#41]
![image](https://user-images.githubusercontent.com/100157077/155058654-ba7b9f3b-7d45-4c89-903b-68cfcdf53e61.png)

**Comment by daushuashd** [comment]
uninstall melon loader then take out all the mods you have then it should fix and the reason why it won't save your progress is that ninja kiwi updated it that modded games don't save so yea

**Comment by Stateofawesome9** [comment]
oh ok
thanks alot
