### ISSUE TITLE
I can only do like 7 upgrades 

### ISSUE THREAD

**Issue by daushuashd** [doombubbles/ultimate-crosspathing#42]
it only makes me do 7 upgrades is it supposed to be like this or is this a bug?

**Comment by daushuashd** [comment]
i found how to do 5-5-5s the issue is ok

**Comment by moneky221** [comment]
how do i do it

**Comment by 4dam3k** [comment]
Default is 7 upgrades but you can change it to max in mod config. Option is named "Execute order 66"
(Game options > mod options > ultimate crosspathing > scroll down)

**Comment by Colamann1** [comment]
haha i saw that all my words had o in it

**Comment by shmoneydummy** [comment]
bro it's so annoying, plsss fix it doomB

**Comment by shmoneydummy** [comment]
> Default is 7 upgrades but you can change it to max in mod config. Option is named "Execute order 66" (Game options > mod options > ultimate crosspathing > scroll down)

how to go to game options??
