### ISSUE TITLE
Crosspath costs bugged out 

### ISSUE THREAD

**Issue by RazorWolvendom** [doombubbles/ultimate-crosspathing#46]
<img width="293" alt="ScreenShot_20220413222858" src="https://user-images.githubusercontent.com/44827474/163265009-f8fa8158-85bf-402f-b1fd-e2079e62e62b.png">

**Comment by doombubbles** [comment]
Please see the FAQ https://github.com/doombubbles/ultimate-crosspathing#quick-answers

**Comment by RazorWolvendom** [comment]
oh my bad, thank you
