### ISSUE TITLE
Ultimate Crosspathing does no effect at all.

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [doombubbles/ultimate-crosspathing#49]
![image](https://user-images.githubusercontent.com/48828036/163575639-15dc6acf-560e-4766-831c-a3b052db8f91.png)

**Comment by Shizune19** [comment]
Yup. same here and hopefully doombubbles see this error and try to fix

**Comment by VIPer3per** [comment]
Same. the upgrades just lock out, the exact same way the normal upgrades do without the mod.

**Comment by nicotitan** [comment]
same i does nothing
