### ISSUE TITLE
too expensive

### ISSUE THREAD

**Issue by dripsader** [doombubbles/ultimate-crosspathing#50]
when you try to crosspath the price goes up

**Comment by Shizune19** [comment]
That's a bug for sure due to the latest update of the game.

**Comment by ThisIsACoolBoy** [comment]
> when you try to crosspath the price goes up

Check "Quick Answers"; you have probabaly installed mod helper incorrectly/got corrupted, in which  you  have to download it  again.

**Comment by MonoHasJono** [comment]
No, it is indeed the new update that's causing the problem, but for now we can use the unlimited 5th tiers.

**Comment by Colamann1** [comment]
Ehhm as soon as i upgrade 2 paths the third one cost unlimited money
