### ISSUE TITLE
Mod is outdated

### ISSUE THREAD

**Issue by an0nLogin** [doombubbles/ultimate-crosspathing#51]
The mod is not working and throwing errors when trying to regen it, I think that this is caused by the latest update changes.
log files are attached below
[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/8498968/Latest.log)

**Comment by Shizune19** [comment]
I did have issues also to regen the json file for cross pathing as well but I have received this token error too unlike your log file that has no issues in preloading the mod itself.
