### ISSUE TITLE
Repost: Ultimate Crosspathing does nothing at all

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [doombubbles/ultimate-crosspathing#54]
I want to try this mod really bad, but though when installed along with BTD6 Helper, it seems to function like vanilla besides the upgrade bar, could you please look into this problem and give a reply? I would love to try this mod..

**Comment by Jxhnnnnnnn** [comment]
outdated melonloader most likely, its usally 0.5.5 not 0.5.4
