### ISSUE TITLE
Ice Monkey Upgrade Bug

### ISSUE THREAD

**Issue by RazorWolvendom** [doombubbles/ultimate-crosspathing#6]
**[Note this is recorded with the upgrade Cap of 15 instead of 7]** when the Ice Monkey Tower gets the Ability to shoot MOAB-Class with 0-0-5 the Ability doesnt work anymore when these upgrades gets brought: 

First Path
3-0-5 , 4-0-5
Second Path
0-3-5 , 0-4-5

but it works again when the 5th Tier is brought like 5-0-5 or 0-5-5

**Comment by TheLazySquid** [comment]
How did you manage to get the 15 upgrade cap?
