### ISSUE TITLE
It wont work

### ISSUE THREAD

**Issue by Jammydodger9199919** [doombubbles/ultimate-crosspathing#61]
After i updated the game to 32.0 update all my mods just arent working. If anyone knows how to resolve this issue please tell me.

**Comment by Poopermonkinatr** [comment]
i have the same problem

**Comment by Jammydodger9199919** [comment]
I just saw tewitys video and he says mods are broken right now so we just have to wait :)

**Comment by WildArticunoAppeared** [comment]
Yeah, even with the updated mod helper this mod still won't work. Looks like the mod itself will need to be updated here.
