### ISSUE TITLE
Ultimate crosspathing failed to load!

### ISSUE THREAD

**Issue by diebrotwaffel** [doombubbles/ultimate-crosspathing#66]
<img width="588" alt="btd6" src="https://user-images.githubusercontent.com/110742550/183468394-33280a53-a886-42ca-b5d5-b63e2c9d1500.PNG">

**Comment by landedbanana** [comment]
having this same issue

**Comment by Rehso10** [comment]
Same issue here

**Comment by WintechX** [comment]
Yep. Same issue here. Hope dev fixes his broke mod already.

**Comment by gbtm101** [comment]
Also having the same problem, Ultimate Crosspathing and Mod Helper are both up-to-date with current releases.

**Comment by brothy15** [comment]
Having the same Issue
