### ISSUE TITLE
Monkeyopolis Doesn't Recognize Certain Cross-Pathed Banana Farms

### ISSUE THREAD

**Issue by Brewer5700x** [doombubbles/ultimate-crosspathing#67]
You can not upgrade a village from Monkey City to Monkeyopolis even when the following cross-pathed banana farms:

5-4-4
4-5-4
4-4-5
5-5-4
5-4-5
4-5-5
5-5-5

**Comment by gbtm101** [comment]
Not sure how you got the current version of Ultimate Crosspathing to work, but it's intended that Monkeyopolis doesn't absorb Tier 5 Banana Farms. These are all crosspathed with at least one Tier 5 upgrade, and as such are not viable for Monkeyopolis.
