### ISSUE TITLE
I just set max tiers to 7 and this happened

### ISSUE THREAD

**Issue by Brewer5700x** [doombubbles/ultimate-crosspathing#72]
![image](https://user-images.githubusercontent.com/88564659/184383284-febb5455-6960-4595-b76d-269895cc5668.png)

**Comment by tcjde** [comment]
thats because the 32.0 update  i think

**Comment by Jxhnnnnnnn** [comment]
dude setting it to 7 makes the mob bug out and the upgrades cost 340,282,300,000,000,000,000,000,000,000,000,000,000
