### ISSUE TITLE
crosspaths not working at all

### ISSUE THREAD

**Issue by nLaykon** [doombubbles/ultimate-crosspathing#73]
# Tower Behavior Improvement

### Mod Version

1.3.2

### Mod Helper Version

3.0.1

### Tower Crosspaths

seemingly all towers

### Description

when crosspathing, you cannot buy all 3 paths and or 3rd tier on multiple paths
![image](https://user-images.githubusercontent.com/88331977/185256479-25c45ca7-6385-4f87-8e7e-d68272394d16.png)
![image](https://user-images.githubusercontent.com/88331977/185256505-2c887681-5240-438c-90dc-f46a2ac70799.png)
and when you click off and back on the tower it returns to normal non-modded almost
![image](https://user-images.githubusercontent.com/88331977/185256588-cedef922-5cba-429a-b7ad-5550791d8055.png)

**Comment by thordat** [comment]
![Uploading image.png…]()
It's returning a really large number upon inputting at least a 2-1-0 or 2-0-1 upgrade.

**Comment by stumpyalex** [comment]
Having the same problem. Everything is up to date

**Comment by BtdIscool** [comment]
Having the same issue

**Comment by Nightmare108** [comment]
> 

Can you make sure that the unlimited cross pathing does not have am error when downloading the mod plz have a good day sir,
