### ISSUE TITLE
Can't Download 1.3.3 Through Mod Helper Mod Browser

### ISSUE THREAD

**Issue by Brewer5700x** [doombubbles/ultimate-crosspathing#75]
# Installation Error
Can't Download 1.3.3 Through Mod Helper Mod Browser

### Mod Version
1.3.3

### Mod Helper Version

3.0.1

### Description

I can't download Ultimate Crosspathing version 1.3.3 through the mod helper mod browser

### Other Mods

![image](https://user-images.githubusercontent.com/88564659/186906723-0209c21f-43d7-48d9-9334-ee14c25982fc.png)

### Logs
[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/9433269/Latest.log)

**Comment by doombubbles** [comment]
As the screenshot shows, Ultimate Crosspathing has a much larger file size than most other mods. If your internet connection is on the spotty side, you may need to increase the request timeout option in the Mod Helper Settings.

![Settings Screenshot](https://media.discordapp.net/attachments/800115046134186026/1012882202167607306/unknown.png?width=1158&height=670)
