### ISSUE TITLE
Upgrade bug.

### ISSUE THREAD

**Issue by BMNaruto** [doombubbles/ultimate-crosspathing#80]
basically every time i try to upgrade the tower it doies not show i upgraded it and when i try to crosspath the cost goes from the normal cost to like this (1,707,424,423,234,924,234,234,234,734,423,234,234,429,423,223,423,234,234,234,423)

**Comment by Kosmic-Gamer** [comment]
Hi, That is because you have the wrong version of BTD 6 Mod Helper, To download the latest one visit https://github.com/gurrenm3/BTD-Mod-Helper/releases/ and download the latest one and drag and drop it from your downloads to the mods folder

**Comment by BMNaruto** [comment]
Ok, thank you so much, but i alreadyfigured out the problem and i am
enjoying your mods very much!
😅😅😅
