### ISSUE TITLE
It says it doesn't work for latest Melon Loader version

### ISSUE THREAD

**Issue by BogdanolRoblox** [doombubbles/ultimate-crosspathing#81]
So I downloaded the mod, I set it up and everything and when I launched the game it said it doesn't work for the latest Melon Loader version. I checked it out and it seems the mod version was outdated so I updated it. But then it just didn't work. I re-launched the game but nothing. I tried a few things, like re-downloading Melon Loader, but nothing works. I can only have two paths. I'm out of ideas.

**Comment by baderormous** [comment]
do you have btd mod helper if u don't The mod doesn't work
