### ISSUE TITLE
crash towers and shut down 

### ISSUE THREAD

**Issue by stayrale** [doombubbles/ultimate-crosspathing#89]
# Tower Crash / Fail

Mod Version = 1.3.6

Mod Helper Version = 3.1.2

Tower Crosspaths, Description

[Monkey Buccaneer] 3XX(X is over 2) 
and
[Monkey Village] 2XX(X is over 2)

these two tower have crash when upgrade first path over 3~2. 
if upgrade it, game freeze and shut down.
If the upgrade of another path is performed normally as if there is no mode, the upgrade is possible, but if the upgrade of 0XX exceeds 2 as if using the mode, it becomes a conflict.
I tried touching various settings to solve the bug, but it didn't work out.

Other Mods = unlimited 5tiers, powers in shop 

I'm sorry do used a translator. not good at English XD

**Comment by doombubbles** [comment]
Crashes like these are fixed with the latest [MelonLoader 0.6.1 update](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer
