### ISSUE TITLE
No Compatibility

### ISSUE THREAD

**Issue by Jonyboylovespie** [doombubbles/ultimate-crosspathing#9]
Whenever I load Into MelonLoader With ModHelper On It Says "[10:36:11.415] [ERROR] Failed to Load Assembly for C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Mods\UltimateCrosspathing.dll: No Compatibility Layer Found!"

**Comment by atomix187** [comment]
same here

**Comment by Jonyboylovespie** [comment]
I figured it out @atomix187 you have to download modhelper and take both files out of the zip and then download nkhook6 here https://nkhook.com/pages/bloons6.html

**Comment by MagicGonads** [comment]
you do not need nkhook

**Comment by EnigmaboyzFX** [comment]
can you send a updated link, or a new mod helper please this ones out dated. cheers
