### ISSUE TITLE
Tier Limiter Doesn't Work

### ISSUE THREAD

**Issue by LJ-Master** [doombubbles/ultimate-crosspathing#92]
When trying to limit tiers with the crosspath mod, the towers will still display and allow you to upgrade past the tier requested.
![Screenshot_20230204_043401](https://user-images.githubusercontent.com/124460815/216792439-032a40de-8819-4b64-9e3e-4fabb5cbe9f3.png)

Crosspath Mod Version 1.3.6

Mod Helper Version 3.1.3

Mod Helper Version 3.1.3

When I set the tiers to 0 zero, I shouldn't be able to upgrade my towers, instead the game displays and allows me to upgrade my towers even though i set it to 0 tiers.
![Screenshot_20230204_043201](https://user-images.githubusercontent.com/124460815/216792412-50468035-6db4-46df-b4d2-452ea3d98135.png)

I was trying to use your ascended upgrades mod so I can upgrade 0-0-0 towers with it, but since it thinks I can upgrade the towers, the ascended upgrades mod will not work.(unless I upgrade to tier 5)

The log has no errors or anything that would say that something didn't go correctly,

**Comment by doombubbles** [comment]
I think in the next update I will change the minimum value to 7, because it was never really intended to restrict which vanilla upgrades you can normally take. Stuff like the challenge editor seems more appropriate for actually trying to accomplish that
