### ISSUE TITLE
Upgrading Towers crashes the game (ship, icemonkey..)

### ISSUE THREAD

**Issue by Yorukun12** [doombubbles/ultimate-crosspathing#99]
# Towiler Crash / Fail

### game crashes instantly, trying to restart and continue crashes again

###fast forward
![Screenshot 2023-02-18 194155](https://user-images.githubusercontent.com/125762307/219882838-c298235d-6390-4469-a159-c8aa99b80d41.png)

**Comment by DarkNebulousSpaector** [comment]
I have the issue with Ship and Village.

**Comment by ERAMYT** [comment]
I had this issue but I had like 6, 4-2-4 farms and it was a lot of towers and money. It also crashed when I had a 5-5-5 village

**Comment by doombubbles** [comment]
Crashes like these are fixed with the latest [MelonLoader 0.6.1 update](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer
